---
apiVersion: v1
kind: Namespace
metadata:
  name: kubestro

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: kubestro
type: kubernetes.io/basic-auth
stringData:
  username: kubestro
  password: kubestro

---
# cnpg cluster
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: kubestro
  namespace: kubestro
spec:
  instances: 1

  bootstrap:
    initdb:
      database: kubestro
      owner: kubestro
      secret:
        name: app-secret

  storage:
    size: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: kubestro-pg
  namespace: kubestro
spec:
  type: LoadBalancer
  selector:
    cnpg.io/cluster: kubestro
    cnpg.io/podRole: instance
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
