---
version: 3

tasks:
  default:
    silent: true
    cmd: go-task -l

  dev:
    desc: "Start development server"
    cmd: nx dev

  install:
    desc: Install dependencies
    cmd: pnpm i

  lint:
    desc: Lint the project
    cmd: nx run-many -t lint:js,lint:css --parallel -p @kubestro/core-frontend

  build:
    desc: Build the project
    cmds:
      - nx build
    sources:
      - src/**/*.{ts,css,tsx}
    generates:
      - dist
