packages:
  - .
  - projects/libraries/design-system
  - projects/libraries/eslint-config
  - projects/services/kubestro-core/frontend
catalog:
  "@eslint/js": ^9.18.0
  "@react-router/dev": ^7.1.1
  "@react-router/node": ^7.1.1
  "@react-router/serve": ^7.1.1
  "@stylistic/eslint-plugin": ^2.12.1
  "@types/node": ^20
  "@types/react": ^19.0.5
  "@types/react-dom": ^19.0.3
  "@vitejs/plugin-react-swc": ^3.5.0
  autoprefixer: ^10.4.20
  cross-env: ^7.0.3
  eslint: ^9.18.0
  eslint-plugin-jsx-a11y: ^6.10.2
  eslint-plugin-react: ^7.37.3
  eslint-plugin-react-hooks: ^5.1.0
  eslint-plugin-react-refresh: ^0.4.16
  globals: ^15.14.0
  isbot: ^5.1.17
  postcss: ^8.4.49
  prettier: ^3.4.2
  prettier-plugin-toml: 2.0.1
  react: ^19.0.0
  react-dom: ^19.0.0
  react-router: ^7.1.1
  stylelint: ^16.13.0
  stylelint-config-standard: ^37.0.0
  stylelint-config-tailwindcss: ^0.0.7
  tailwindcss: ^3.4.16
  typescript: ~5.6.2
  typescript-eslint: ^8.19.1
  vite: ^6.0.7
  vite-tsconfig-paths: ^5.1.4
