packages:
  - .
  - projects/libraries/design-system
  - projects/libraries/eslint-config
  - projects/services/kubestro-core/frontend
catalog:
  "@react-router/dev": ^7.1.1
  "@react-router/node": ^7.1.1
  "@react-router/serve": ^7.1.1
  "@stylistic/eslint-plugin": ^2.12.1
  "@types/node": ^20
  "@vitejs/plugin-react-swc": ^3.5.0
  autoprefixer: ^10.4.20
  cross-env: ^7.0.3
  eslint: ^9.18.0
  eslint-plugin-jsx-a11y: ^6.10.2
  eslint-plugin-react: ^7.37.3
  eslint-plugin-react-refresh: ^0.4.16
  globals: ^15.14.0
  isbot: ^5.1.17
  postcss: ^8.4.49
  prettier: ^3.4.2
  prettier-plugin-toml: 2.0.1
  react-router: ^7.1.1
  tailwindcss: ^3.4.16
  typescript: ~5.6.2
  vite-tsconfig-paths: ^5.1.4
