packages:
  - .
  - projects/libraries/design-system
  - projects/libraries/eslint-config
  - projects/services/kubestro-core/frontend
catalog:
  "@eslint/js": ^9.18.0
  "@fontsource-variable/inter": ^5.1.1
  "@module-federation/runtime": ^0.8.9
  "@module-federation/vite": ^1.2.1
  "@monodon/rust": ^2.1.1
  "@nx/eslint": 20.4.0
  "@nx/module-federation": 20.4.0
  "@nx/storybook": 20.4.0
  "@nx/vite": 20.4.0
  "@nx/web": 20.4.0
  "@nx/workspace": ^20.4.0
  "@radix-ui/react-checkbox": ^1.1.3
  "@radix-ui/react-label": ^2.1.1
  "@radix-ui/react-slot": ^1.1.1
  "@react-router/dev": ^7.1.3
  "@react-router/node": ^7.1.3
  "@react-router/serve": ^7.1.3
  "@storybook/addon-a11y": ^8.5.1
  "@storybook/addon-actions": ^8.5.1
  "@storybook/addon-essentials": ^8.5.1
  "@storybook/addon-interactions": ^8.5.1
  "@storybook/addon-links": ^8.5.1
  "@storybook/addon-onboarding": ^8.5.1
  "@storybook/addon-themes": ^8.5.1
  "@storybook/blocks": ^8.5.1
  "@storybook/react": ^8.5.1
  "@storybook/react-vite": ^8.5.1
  "@storybook/test": ^8.5.1
  "@stylistic/eslint-plugin": ^3.0.0
  "@swc-node/register": ^1.10.9
  "@swc/core": ^1.10.12
  "@tailwindcss/vite": ^4.0.0
  "@types/node": ^22.0.0
  "@types/react": ^19.0.5
  "@types/react-dom": ^19.0.3
  "@vitejs/plugin-react-swc": ^3.5.0
  "@vitest/ui": ^3.0.4
  autoprefixer: ^10.4.20
  cross-env: ^7.0.3
  eslint: ^9.18.0
  eslint-plugin-import: ^2.31.0
  eslint-plugin-jsx-a11y: ^6.10.2
  eslint-plugin-react: ^7.37.3
  eslint-plugin-react-hooks: ^5.2.0-canary-9b62ee71-20250122
  eslint-plugin-storybook: ^0.11.2
  eslint-plugin-tailwindcss: ^3.17.5
  eslint-plugin-unused-imports: ^4.1.4
  globals: ^15.14.0
  isbot: ^5.1.17
  lucide-react: ^0.474.0
  nx: 20.4.0
  postcss: ^8.4.49
  prettier: ^3.4.2
  prettier-plugin-toml: 2.0.1
  react: ^19.0.0
  react-dom: ^19.0.0
  react-router: ^7.1.3
  storybook: ^8.5.2
  stylelint: ^16.13.2
  stylelint-config-standard: ^37.0.0
  tailwind-merge: ^3.0.0
  tailwind-variants: ^0.3.1
  tailwindcss: ^4.0.0
  typescript: ~5.7.3
  typescript-eslint: ^8.19.1
  vite: ^6.0.11
  vite-plugin-dts: ^4.5.0
  vite-tsconfig-paths: ^5.1.4
  vitest: ^3.0.4
