# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

dotenv:
  - "projects/api/.env"

includes:
  api:
    taskfile: ./projects/api/Taskfile.yml
    dir: ./projects/api

tasks:
  ui:
    dir: ./projects/webui
    cmds:
      - pnpm run dev
  build-ui:
    dir: ./projects/webui
    cmds:
      - pnpm run build
