---
version: 3

includes:
  core: ./projects/services/kubestro-core/Taskfile.yaml
  design-system: ./projects/libraries/design-system/Taskfile.yaml

tasks:
  default:
    silent: true
    cmd: go-task -l

  install:
    desc: Install dependencies
    cmds:
      - pnpm i

  format:
    desc: Format files
    cmds:
      - prettier --write . --config .prettierrc.yaml

  sync-deps:
    desc: Sync dependencies
    cmds:
      - pnpm dlx codemod pnpm/catalog
