version: 3

dotenv:
  - .env

includes: {}

tasks:
  default:
    silent: true
    cmd: go-task -l

  install:
    desc: Install dependencies
    cmds:
      - task: deps
      - cp -n .env.example .env

  deps:
    desc: Install project dependencies
    cmds:
      - pnpm i

  format:
    desc: Format files
    cmds:
      - prettier --write .

