---
version: 3

tasks:
  default:
    silent: true
    cmd: go-task -l

  install:
    desc: Install dependencies
    cmds:
      - pnpm i

  dev:
    desc: "Start development server"
    cmd: pnpm run dev

  build:
    desc: Build the project
    cmds:
      - pnpm build

  format:
    desc: Format files
    cmds:
      - prettier --write .
