---
version: 3

tasks:
  default:
    silent: true
    cmd: go-task -l

  install:
    desc: Install dependencies
    cmds:
      - pnpm i

  dev:
    desc: "Start development server"
    cmd: nx dev

  build:
    desc: Build the project
    cmds:
      - nx build

  story:
    desc: Start storybook
    cmd: nx storybook
