//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "user_provider")]
pub enum UserProvider {
    #[sea_orm(string_value = "local")]
    Local,
    #[sea_orm(string_value = "oidc")]
    Oidc,
}
