[package]
name = "kubestro-core"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
axum = "0.8.1"
dotenvy = { workspace = true }
serde = { workspace = true }
sea-orm = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tower-http = { version = "0.6.2", features = ["trace", "timeout"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
validator = "0.20.0"

# sea-orm
entity = { path = "../entity" }
migration = { path = "../migration" }
