---
version: 3

tasks:
  default:
    silent: true
    cmd: go-task -l

  dev:
    desc: "Start development server"
    dotenv:
      - .env
    cmd: cargo watch -x 'run --bin kubestro-core {{.CLI_ARGS}}'

  lint:
    desc: Lint the project
    cmd: cargo clippy --all-targets

  build:
    desc: Build the project
    cmd: cargo build
    sources:
      - src/**/*.rs
    generates:
      - target/debug/kubestro-core

  format:
    desc: Format files
    cmds:
      - cargo fmt -- --config-path ../../../../configs/rustfmt.toml

  # sea-orm migrations
  migrate:up:
    desc: Create a new migration
    cmd: sea-orm-cli migrate up -d ./migration/

  migrate:down:
    desc: Rollback the last migration
    cmd: sea-orm-cli migrate down -d ./migration/

  migrate:reset:
    desc: Reset the database
    cmd: sea-orm-cli migrate reset -d ./migration/

  migrate:refresh:
    desc: Refresh the database
    cmd: sea-orm-cli migrate refresh -d ./migration/

  generate-entity:
    desc: Generate a new entity
    cmd: sea-orm-cli generate entity -o ./infra/src/entities/ --with-serde both --serde-skip-hidden-column --serde-skip-deserializing-primary-key --date-time-crate chrono
