---
name: Format check

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop

  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read
  checks: write

env:
  NX_CACHE: cache-nx
  DEPENDENCIES_CACHE: cache-node-modules

jobs:
  install-deps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Restore Cache if it exists
        uses: actions/cache@v4
        id: cache
        with:
          path: node_modules
          key: ${{ env.DEPENDENCIES_CACHE }}-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: "10.5"
          run_install: false
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Setup Node.JS
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"
        if: steps.cache.outputs.cache-hit != 'true'

      - name: pnpm install
        if: steps.cache.outputs.cache-hit != 'true'
        run: pnpm install --frozen-lockfile

  format:
    runs-on: ubuntu-latest
    needs: [install-deps]

    strategy:
      matrix:
        target: ["format:check"]
        jobIndex: [1, 2, 3, 4]

    env:
      jobCount: 4

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: "10.5"

      - name: Setup Node.JS
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ env.DEPENDENCIES_CACHE }}-${{ hashFiles('pnpm-lock.yaml') }}

      # this task is a fix to reconstruct node_modules in workspace projects after the cache
      - name: pnpm install
        run: pnpm install --frozen-lockfile

      - name: Cache NX
        uses: actions/cache@v4
        with:
          path: .nx
          key: ${{ env.NX_CACHE }}-${{ hashFiles('pnpm-lock.yaml') }}-${{ matrix.target }}-${{ github.sha }}
          restore-keys: |
            ${{ env.NX_CACHE }}-${{ hashFiles('pnpm-lock.yaml') }}-${{ matrix.target }}-${{ matrix.jobIndex }}-
            ${{ env.NX_CACHE }}-${{ hashFiles('pnpm-lock.yaml') }}-
            ${{ env.NX_CACHE }}-

      - run: git fetch --no-tags --prune --depth=1 origin main

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v4

      - name: nx run-many:${{ matrix.target }}
        run: node ./configs/run-many.mjs "${{ matrix.target }}" "${{ matrix.jobIndex }}" "${{ env.jobCount }}" "$GITHUB_REF" "${{ env.NX_BASE }}"
