---
name: Remove approvals when PR diff changes

on:
  pull_request:
    # Here, 'opened' is important because it allows the action to
    # see the initial PR diff and compare it later.
    types: [opened, edited, synchronize]
    branches:
      - main
      - develop

jobs:
  waitaminute:
    runs-on: ubuntu-latest
    steps:
      - uses: petalmd/waitaminute@v2
        with:
          dismiss-message: Review dismissed because the PR has changed.
